# Generated by Django 4.0.5 on 2022-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.FloatField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('release', models.DateField()),
                ('lte', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
